server:
  port: 8082

spring:
  application:
    name: provider-1
eureka:
  client:
    service-url:
      defaultZone: http://lijun:1234@localhost:8761/eureka/
  instance:
    prefer-ip-address: true