spring:
  application:
    name: auth-server

server:
  port: 8084
eureka:
  client:
    service-url:
      defaultZone: http://lijun:1234@localhost:8761/eureka/
    healthcheck:
      enabled: true

  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 5